### ISSUE TITLE
normalizing joint length

### ISSUE THREAD

**Issue by FNRocha** [CalciferZh/AMCParser#4]
First of all, I would like to thank you for this work. I am very impressed, this is extremely helpful and I am planning in using it for my master thesis. In order to do that on the other hand I would need to perform joint normalization, so joints would be the same length in different animations?
Can you provide any idea of how can I change that?

**Comment by CalciferZh** [comment]
[This page](https://research.cs.wisc.edu/graphics/Courses/cs-838-1999/Jeff/ASF-AMC.html) might be helpful for you. I think you can change the bone length field in the `.asf` file directly.
